import { Claim } from '../models';

export const MOCK_CLAIMS: Claim[] = [
  { id: 'C001', itemId: 'F001', itemName: 'Student ID Card', claimantId: 'u2', claimantName: 'Sarah Chen', claimantEmail: 'sarah.chen@campus.edu', description: 'This is my student ID card. I lost it near the cafeteria on April 28th.', proofDescription: 'The ID has my full name Sarah Chen, photo, and student number BA-2024-0322.', status: 'approved', submittedDate: '2026-04-30', reviewedDate: '2026-05-01', reviewedBy: 'Maria Santos', adminNotes: 'Identity verified against student records. ID returned.' },
  { id: 'C002', itemId: 'F002', itemName: 'Silver Watch', claimantId: 'u7', claimantName: 'Tom Baker', claimantEmail: 'tom.baker@campus.edu', description: 'I believe this is my Casio watch. I was sitting on that bench studying last week.', proofDescription: 'It is a Casio A168WA model. The back has a small scratch near the serial number.', status: 'pending', submittedDate: '2026-05-03' },
  { id: 'C003', itemId: 'F003', itemName: 'Wireless Earbuds', claimantId: 'u1', claimantName: 'Alex Rivera', claimantEmail: 'alex.rivera@campus.edu', description: 'These are my AirPods. I was studying on the 3rd floor and left them behind.', proofDescription: 'The case has a small dent on the bottom-left corner. They are paired with my iPhone.', status: 'pending', submittedDate: '2026-05-04' },
  { id: 'C004', itemId: 'F005', itemName: 'Calculator (TI-84)', claimantId: 'u5', claimantName: 'David Kim', claimantEmail: 'david.kim@campus.edu', description: 'This is my graphing calculator. The initials DK stand for David Kim.', proofDescription: 'My initials DK are written on the back in silver marker. The battery cover has tape on it.', status: 'rejected', submittedDate: '2026-05-05', reviewedDate: '2026-05-06', reviewedBy: 'Maria Santos', adminNotes: 'Initials match but description of battery cover does not match the found item. Claim denied.' },
  { id: 'C005', itemId: 'F004', itemName: 'Umbrella (Black)', claimantId: 'u3', claimantName: 'Dr. James Wilson', claimantEmail: 'j.wilson@campus.edu', description: 'I left my umbrella in the admin building lobby during a meeting.', proofDescription: 'It has a wooden J-shaped handle with a small brass ring at the tip.', status: 'pending', submittedDate: '2026-05-06' },
];
