import { Item } from '../models';

export const MOCK_LOST_ITEMS: Item[] = [
  { id: 'L001', name: 'MacBook Pro 14"', category: 'Electronics', description: 'Space gray MacBook Pro with a blue case and "CS Dept" sticker on the lid.', location: 'Library - 2nd Floor Study Area', date: '2026-05-01', department: 'Computer Science', campus: 'Main Campus', status: 'pending', type: 'lost', image: 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=400', contactName: 'Alex Rivera', contactEmail: 'alex.rivera@campus.edu', contactPhone: '+1 555-0101', reportedBy: 'u1', reportedDate: '2026-05-01' },
  { id: 'L002', name: 'Student ID Card', category: 'ID/Cards', description: 'University student ID card with name Sarah Chen and photo.', location: 'Cafeteria - Main Hall', date: '2026-04-28', department: 'Business Administration', campus: 'Main Campus', status: 'matched', type: 'lost', contactName: 'Sarah Chen', contactEmail: 'sarah.chen@campus.edu', reportedBy: 'u2', reportedDate: '2026-04-28' },
  { id: 'L003', name: 'Blue Backpack (Herschel)', category: 'Bags', description: 'Navy blue Herschel backpack with a water bottle in the side pocket and notebooks inside.', location: 'Engineering Building - Room 201', date: '2026-04-30', department: 'Engineering', campus: 'Main Campus', status: 'pending', type: 'lost', image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=400', contactName: 'Tom Baker', contactEmail: 'tom.baker@campus.edu', reportedBy: 'u7', reportedDate: '2026-04-30' },
  { id: 'L004', name: 'Car Keys (Toyota)', category: 'Keys', description: 'Toyota car key with a red lanyard and campus parking tag attached.', location: 'Parking Lot B', date: '2026-05-02', department: 'Sciences', campus: 'North Campus', status: 'claimed', type: 'lost', contactName: 'Prof. Linda Okafor', contactEmail: 'l.okafor@campus.edu', reportedBy: 'u6', reportedDate: '2026-05-02' },
  { id: 'L005', name: 'iPhone 15 Pro', category: 'Electronics', description: 'Black iPhone 15 Pro with a clear case and cracked screen protector.', location: 'Gymnasium - Locker Room', date: '2026-05-03', department: 'Computer Science', campus: 'Main Campus', status: 'pending', type: 'lost', image: 'https://images.unsplash.com/photo-1592750475338-74b7b21085ab?w=400', contactName: 'David Kim', contactEmail: 'david.kim@campus.edu', reportedBy: 'u5', reportedDate: '2026-05-03' },
  { id: 'L006', name: 'Calculus Textbook', category: 'Books', description: 'Stewart Calculus 9th Edition with highlighted pages and sticky notes throughout.', location: 'Science Building - Lecture Hall A', date: '2026-04-25', department: 'Sciences', campus: 'Main Campus', status: 'pending', type: 'lost', contactName: 'Emily Nguyen', contactEmail: 'emily.nguyen@campus.edu', reportedBy: 'u8', reportedDate: '2026-04-25' },
  { id: 'L007', name: 'Prescription Glasses', category: 'Accessories', description: 'Black-framed prescription glasses in a brown leather case.', location: 'Student Union - Meeting Room 3', date: '2026-05-04', department: 'Arts & Design', campus: 'Main Campus', status: 'pending', type: 'lost', contactName: 'Alex Rivera', contactEmail: 'alex.rivera@campus.edu', reportedBy: 'u1', reportedDate: '2026-05-04' },
  { id: 'L008', name: 'USB Flash Drive (64GB)', category: 'Electronics', description: 'SanDisk 64GB USB drive with a green cap, contains senior project files.', location: 'Computer Lab - Room 105', date: '2026-05-05', department: 'Computer Science', campus: 'Main Campus', status: 'pending', type: 'lost', contactName: 'Tom Baker', contactEmail: 'tom.baker@campus.edu', reportedBy: 'u7', reportedDate: '2026-05-05' },
];

export const MOCK_FOUND_ITEMS: Item[] = [
  { id: 'F001', name: 'Student ID Card', category: 'ID/Cards', description: 'University student ID found on the floor near the entrance. Name visible: Sarah C.', location: 'Cafeteria - Near Entrance', date: '2026-04-29', department: 'Student Affairs', campus: 'Main Campus', status: 'matched', type: 'found', contactName: 'Maria Santos', contactEmail: 'maria.santos@campus.edu', reportedBy: 'u4', reportedDate: '2026-04-29', pickupLocation: 'Student Affairs Office - Room 101', verificationNotes: 'ID appears to belong to a Business Admin student.' },
  { id: 'F002', name: 'Silver Watch', category: 'Accessories', description: 'Casio silver wristwatch found on a bench.', location: 'Campus Garden - Central Bench', date: '2026-05-01', department: 'Student Affairs', campus: 'Main Campus', status: 'pending', type: 'found', image: 'https://images.unsplash.com/photo-1524592094714-0f0654e20314?w=400', contactName: 'Dr. James Wilson', contactEmail: 'j.wilson@campus.edu', reportedBy: 'u3', reportedDate: '2026-05-01', pickupLocation: 'Engineering Building - Faculty Office 305' },
  { id: 'F003', name: 'Wireless Earbuds', category: 'Electronics', description: 'White wireless earbuds in a charging case found under a desk.', location: 'Library - 3rd Floor Computer Area', date: '2026-05-02', department: 'Student Affairs', campus: 'Main Campus', status: 'pending', type: 'found', image: 'https://images.unsplash.com/photo-1590658268037-6bf12f032f55?w=400', contactName: 'Emily Nguyen', contactEmail: 'emily.nguyen@campus.edu', reportedBy: 'u8', reportedDate: '2026-05-02', pickupLocation: 'Library - Information Desk' },
  { id: 'F004', name: 'Umbrella (Black)', category: 'Other', description: 'Large black umbrella with a wooden handle left in the lobby.', location: 'Admin Building - Main Lobby', date: '2026-05-03', department: 'Student Affairs', campus: 'Main Campus', status: 'pending', type: 'found', contactName: 'Maria Santos', contactEmail: 'maria.santos@campus.edu', reportedBy: 'u4', reportedDate: '2026-05-03', pickupLocation: 'Admin Building - Reception' },
  { id: 'F005', name: 'Calculator (TI-84)', category: 'Electronics', description: 'Texas Instruments TI-84 Plus graphing calculator with initials "DK" on the back.', location: 'Science Building - Room 301', date: '2026-05-04', department: 'Sciences', campus: 'Main Campus', status: 'pending', type: 'found', contactName: 'Prof. Linda Okafor', contactEmail: 'l.okafor@campus.edu', reportedBy: 'u6', reportedDate: '2026-05-04', pickupLocation: 'Sciences Dept Office' },
  { id: 'F006', name: 'Water Bottle (Hydro Flask)', category: 'Other', description: 'Green Hydro Flask water bottle with campus stickers.', location: 'Gymnasium - Weight Room', date: '2026-05-05', department: 'Student Affairs', campus: 'North Campus', status: 'pending', type: 'found', contactName: 'David Kim', contactEmail: 'david.kim@campus.edu', reportedBy: 'u5', reportedDate: '2026-05-05', pickupLocation: 'Gym - Front Desk' },
];
